[repository]
name = "hy3"
authors = ["outfoxxed, DRAGONTOS"]

[hy3]
description = "i3 like tiling for hyprland"
authors = ["outfoxxed, DRAGONTOS"]
output = "build/libhy3.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
	"cmake --build build"
]
